### ISSUE TITLE
Head of development broken on Hera

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#121]
**Describe the bug**

```
esmf-profiler: error: the following arguments are required: -t/--tracedir, -n/--name, -o/--outdir
[venv] [Rocky.Dunlap@hfe04 esmf-profiler]$ esmf-profiler -t tests/fixtures/test-traces/atm-ocn-concurrent -n slug -o ./slug -p git@github.com:esmf-org/app-profiles.git
esmf_profiler.main : Processing trace: tests/fixtures/test-traces/atm-ocn-concurrent
esmf_profiler.main : Generating 1 profiles
Traceback (most recent call last):
  File "/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/venv/bin/esmf-profiler", line 11, in <module>
    load_entry_point('esmf-profiler', 'console_scripts', 'esmf-profiler')()
  File "/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/src/esmf_profiler/main.py", line 234, in main
    push_profile_to_repo(input_path=output_path, name=args.name, url=args.push)
  File "/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/src/esmf_profiler/main.py", line 96, in push_profile_to_repo
    git.clone(url, _temp)
  File "/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/src/esmf_profiler/git.py", line 109, in clone
    return _command_safe(cmd, target_path)
  File "/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/src/esmf_profiler/git.py", line 30, in _command_safe
    encoding="utf-8",
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
[venv] [Rocky.Dunlap@hfe04 esmf-profiler]$ which python3
/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/venv/bin/python3
[venv] [Rocky.Dunlap@hfe04 esmf-profiler]$ python3 --version
Python 3.6.8
```

This might be related to Python 3.6.8 because head of development does work on 3.9.5.

**Comment by ryanlong1004** [comment]
Python <3.7 does not support ```capture_output``` for subprocess.run.

![image](https://user-images.githubusercontent.com/69773028/142917558-a944a07a-789b-4d49-8302-16e4acf5330d.png)

Verified pushing to Github.

![image](https://user-images.githubusercontent.com/69773028/142917404-607f8f27-e142-47f6-af13-b154389d7b4a.png)
